#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

COUCHDB_USERNAME = data.get("couchdb_username", "")
COUCHDB_PASS = data.get("couchdb_password", "")
HOST = data.get("host", "")
app_config = {
    "COUCHDB_USER": COUCHDB_USERNAME,
    "COUCHDB_PASSWORD": COUCHDB_PASS,
    "HOST": HOST,
    "COUCHDB_BIND_ADDRESS": "0.0.0.0",
    "COUCHDB_CREATE_DATABASES": "yes",
    "COUCHDB_SINGLE_NODE": "true",
    "CONFIGURED": True,
}
agent.write_envfile("couchdb.env", app_config)

# This is specific to you module, so you need to change it accordingly.
# agent.dump_env()
