#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

COUCHDB_USERNAME = data.get("couchdb_username", "")
COUCHDB_PASS = data.get("couchdb_password", "")
app_config = {"COUCHDB_USERNAME": COUCHDB_USERNAME, "COUCHDB_PASSWORD": COUCHDB_PASS}
agent.write_envfile("couchdb.env", app_config)

# This is specific to you module, so you need to change it accordingly.
# agent.dump_env()
